Api:
  Name: my-api
  Service:
    Name: api
    Type: LoadBalancer
    Ports:
        Protocol: TCP
        OuterPort: 8080
        InnerPort: 80
  Deployment:
    Name: api-deployment
    Replicas: 1
  Image: 
    Name: 993145419620.dkr.ecr.us-west-2.amazonaws.com/kubernetes_containers
    Tag: api-image

FilteredTestJob:
  Name: filtered-test-job
  Image: 
    Name: 993145419620.dkr.ecr.us-west-2.amazonaws.com/kubernetes_containers
    Tag: test-image
  Args: 'Ready=True'

TestJob:
  Name: test-job
  Image: 
    Name: 993145419620.dkr.ecr.us-west-2.amazonaws.com/kubernetes_containers
    Tag: test-image
