apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.Api.Service.Name }}
spec:
  type: {{ .Values.Api.Service.Type }}
  selector:
    app: {{ .Values.Api.Name }}
  ports:
  - protocol: {{ .Values.Api.Service.Ports.Protocol }}
    port: {{ .Values.Api.Service.Ports.OuterPort }}
    targetPort: {{ .Values.Api.Service.Ports.InnerPort }}
