apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.FilteredTestJob.Name }}
  annotations:
    "helm.sh/hook": test-success
spec:
  template:
    spec:
      containers:
      - name: {{ .Values.FilteredTestJob.Name }}
        image: "{{ .Values.FilteredTestJob.Image.Name}}:{{ .Values.FilteredTestJob.Image.Tag}}"
        imagePullPolicy: IfNotPresent
        args: ["{{ .Values.FilteredTestJob.Args }}"]
        env:
        - name: "TEST_TARGET_SERVICE_NAME"
          value: "{{ .Values.Api.Service.Name }}"
        - name: "TEST_TARGET_SERVICE_PORT"
          value: "{{ .Values.Api.Service.Ports.OuterPort }}"
      restartPolicy: Never
